version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.14
  cypress_e2e:
    docker:
      - image: benaud12/cypress-tester:latest

commands:
  say_hello:
    description: 'Simply saying hello'
    parameters:
      to:
        type: string
        default: 'nobody'
    steps:
      - run: echo Hello there << parameters.to >>

  say_goodbye:
    description: 'Simply saying goodbye'
    parameters:
      to:
        type: string
        default: 'nobody'
    steps:
      - run: echo So long << parameters.to >>

jobs:
  say_hello:
    executor: node
    steps:
      - say_hello:
          to: Gav
  cypress_test:
    executor: cypress_e2e
    working_directory: /e2e
    steps:
      - run: yarn cypress:run
      - store_artifacts:
          path: /e2e/cypress/report
          destination: cypress-test-report
  say_goodbye:
    executor: node
    steps:
      - say_goodbye:
          to: Mick

workflows:
  testing:
    jobs:
      - say_hello
      - cypress_test:
          requires:
            - say_hello
      - approve_tests:
          type: approval
          requires:
            - cypress_test
      - say_goodbye:
          requires:
            - approve_tests
